// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/test4/test4.proto

package go_micro_srv_test4

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Test4 service

type Test4Service interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Test4_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Test4_PingPongService, error)
}

type test4Service struct {
	c    client.Client
	name string
}

func NewTest4Service(name string, c client.Client) Test4Service {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.test4"
	}
	return &test4Service{
		c:    c,
		name: name,
	}
}

func (c *test4Service) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Test4.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *test4Service) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Test4_StreamService, error) {
	req := c.c.NewRequest(c.name, "Test4.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &test4ServiceStream{stream}, nil
}

type Test4_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type test4ServiceStream struct {
	stream client.Stream
}

func (x *test4ServiceStream) Close() error {
	return x.stream.Close()
}

func (x *test4ServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *test4ServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *test4ServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *test4ServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *test4Service) PingPong(ctx context.Context, opts ...client.CallOption) (Test4_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Test4.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &test4ServicePingPong{stream}, nil
}

type Test4_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type test4ServicePingPong struct {
	stream client.Stream
}

func (x *test4ServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *test4ServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *test4ServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *test4ServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *test4ServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *test4ServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Test4 service

type Test4Handler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Test4_StreamStream) error
	PingPong(context.Context, Test4_PingPongStream) error
}

func RegisterTest4Handler(s server.Server, hdlr Test4Handler, opts ...server.HandlerOption) error {
	type test4 interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Test4 struct {
		test4
	}
	h := &test4Handler{hdlr}
	return s.Handle(s.NewHandler(&Test4{h}, opts...))
}

type test4Handler struct {
	Test4Handler
}

func (h *test4Handler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.Test4Handler.Call(ctx, in, out)
}

func (h *test4Handler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.Test4Handler.Stream(ctx, m, &test4StreamStream{stream})
}

type Test4_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type test4StreamStream struct {
	stream server.Stream
}

func (x *test4StreamStream) Close() error {
	return x.stream.Close()
}

func (x *test4StreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *test4StreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *test4StreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *test4StreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *test4Handler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.Test4Handler.PingPong(ctx, &test4PingPongStream{stream})
}

type Test4_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type test4PingPongStream struct {
	stream server.Stream
}

func (x *test4PingPongStream) Close() error {
	return x.stream.Close()
}

func (x *test4PingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *test4PingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *test4PingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *test4PingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *test4PingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
